chore: Use indexeddb to persist the query cache
Web storage (localstorage+sessionstorage) has a relatively low size
limit (~5MB), and throws errors when trying to store past that. Here
from firefox:
```
DOMException: The quota has been exceeded.
```

This causes the website to break down, as essentially all queries start
failing.

Replacing this with indexeddb, which should allow for much more storage,
faster access, and native storage of javascript object - removing the
need for superjson.